start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 3 --bjk 0.5 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 6 --bjk 0.5 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 10 --bjk 0.5 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 3 --bjk 1 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 6 --bjk 1 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 10 --bjk 1 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 3 --bjk 2 --method mle --lr 0.005 --max_iter 50
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 6 --bjk 2 --method mle --lr 0.005 --max_iter 50 
start "" /d "../" python new_main.py --data mmb_hard --mmb_clusters 6 --K 10 --bjk 2 --method mle --lr 0.005 --max_iter 50
